version: "3"

services:
  server: &server
    build: server/
    env_file: ./server/server.env
    command:
      - cat
      - build.sh
      # - ./build.sh
    ports:
      - 4321:9393
    # depends_on:
    #   - postgres
    # restart: always

  # postgres:
  #   build: db

  client:
    build: client/
    command: ./install_client_pkg.sh && venora-client
    network_mode: host
    depends_on:
      - server
