version: "3"

services:
  db:
    image: postgres
    container_name: server_db
    env_file: ./db/db.env
    restart: always
    ports:
      - "5432:5432"
    secrets:
      - db-password
    volumes:
      - ./db/ddl:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - isolated
    hostname: db

  server: &server
    build: ./server/
    env_file: ./server/server.env
    volumes:
      - ./server/secrets/password.txt:/run/secrets/db-password
    secrets:
      - db-password
    ports:
      - 4321:9393
    depends_on:
      - db
    networks:
      - isolated
    # restart: always

  client:
    build: client/
    # depends_on:
    #   - server
    networks:
      - isolated

volumes:
  pgdata:
secrets:
  db-password:
    file: db/secrets/password.txt

# Until I figure out a way to automate this connection a little better (maybe hostname instead of IP for connect?)
# To view network for container IPs (for connections)
# docker inspect venora_isolated
networks:
  isolated:
    driver: bridge
